### ISSUE TITLE
Resizing of text box for nodes with narrow widths

### ISSUE THREAD

**Issue by stepsbystep** [dkapur17/streamlit-flow#14]
My main issue here is that the text box for a node doesn't seem to resize with the height of the node.

Streamlit Flow is a great new component. It looks like it could be just what I need for my app project which involves hierarchically tree-linked lists. 

To use Flow I need to give nodes an interior node structure, a stacked set of nodes within a node. I can do this, as is illustrated in [this file](https://github.com/stepsbystep/stopwatch/blob/main/flowInteraction2A.py). Most everything seems to work well. Particularly, with interaction, clicking on a subnode returns the subnode, while clicking on the node area still properly returns the parent node. 

My principal problem is that specifying the height of a node does not resize the associated text box. I have tried css to correct this, but have found only that setting top padding to zero reduces the problem. Negative padding does not work. In the example code, the left node and subnodes are properly realized. The text for the right node and subnodes with narrower height does not realize properly. 

Additionally, it would be nice to have text for the parent nodes that appears above the stack of subnodes. 

A fix or an explanation of how to use css to solve this problem would be great. 

One additional problem, which I have not extensively investigated yet, is that the edges don't seem to properly display. This may have something to do with the specification of the node types. There doesn't seem to be much documentation about this. I have coded for four edges, but only one is displayed in this example. Any pointers here will be appreciated!

Example file: https://github.com/stepsbystep/stopwatch/blob/main/flowInteraction2A.py

**Comment by yyahav** [comment]
@stepsbystep 

Let's do it step by step ;o)

## Padding issue
> My principal problem is that specifying the height of a node does not resize the associated text box. I have tried css to correct this, but have found only that setting top padding to zero reduces the problem. Negative padding does not work. In the example code, the left node and subnodes are properly realized. The text for the right node and subnodes with narrower height does not realize properly.

I saw your code, well done on trying various css options, I've been there as well :)
This issue is caused due to the default `margin-top: 8px` css settings for the paragraph within the node, you can see when inspecting the node:

<img src="https://github.com/user-attachments/assets/6a65cb8f-355a-4ede-8924-94f5d81e838c" width=500>

To address this issue you need to enter your `content` data with specific paragraph styling, and add zero padding to the node:
```
StreamlitFlowNode('24', (300, 250), {'content': '<p style="margin: 0; padding: 0; font-weight: 400;">Node 2-4</p>'}, 'output', target_position='left', draggable=True,
                      width=100, height=25, style={ "padding": 0 }),
```

**Also a note** - `padding` doesn't support negative values, only `margin` does. Negatives are considered 0.


## Parent text
> Additionally, it would be nice to have text for the parent nodes that appears above the stack of subnodes.
> 
> A fix or an explanation of how to use css to solve this problem would be great.

Just change the parent height, so the subnodes won't hide the parent text from view, the text is on top, and you can use the previous method to control where the text appears on the parent.
In any case, in React Flow there's a node type called `group` which is exactly what you're trying to achieve.
When I'll have some time I'll add this type to `streamlit-flow` in the next version, it should be easier than using an input/output node for it.

<img width="200" alt="image" src="https://github.com/user-attachments/assets/702a1504-3154-4158-8f7f-5e963f06d708">


## Edges issue
> One additional problem, which I have not extensively investigated yet, is that the edges don't seem to properly display. This may have something to do with the specification of the node types. There doesn't seem to be much documentation about this. I have coded for four edges, but only one is displayed in this example. Any pointers here will be appreciated!

The nodes currently have 3 types: `default`, `input`, `output`
*default* - has two connections - input and output
*input*/*output* - has one connection to be used as input or output respectively.

When initializing a `StreamlitFlowNode()` object, you have these parameters:
*node_type* - choose one of the 3 types above, according to the use case.
*source_position* - if the node is of `input` type, this determines where the "out" edge connection resides (**out of** the **input** node) 
*target_position* - if the node is of `output` type, this determines where the "in" edge connection resides (**into** the **output** node)

So if your edges are configured like this:
```
edges = [
    StreamlitFlowEdge('14-21', '14', '21', animated=True),
    StreamlitFlowEdge('11-23', '11', '23', animated=True),
    StreamlitFlowEdge('12-21', '12', '21', animated=True),
    StreamlitFlowEdge('13-24', '13', '24', animated=True)
]
```

The `input` nodes are - 14, 11, 12 and 13
The `output` nodes are - 21, 23 and 24

Once you configure the nodes types and connections properly, it all renders as expected:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/107cfa3b-0bd6-40d1-ae6e-2b67755360d4">

This is the code:
```
nodes = [
    StreamlitFlowNode(id='10', pos=(90, 90), data={'content': "Node 1-0"},  node_type='output', draggable=False,
                      width=120, height=220),
    StreamlitFlowNode(id='11', pos=(100, 100), data={'content': "Node 1-1"},  node_type='input', source_position='right', draggable=False,
                      width=100, height=50),
    StreamlitFlowNode('12', (100, 150), {'content': 'Node 1-2'}, 'input', 'right', draggable=False,
                      width=100, height=50),
    StreamlitFlowNode('13', (100, 200), {'content': 'Node 1-3'}, 'input', 'right', draggable=False,
                      width=100, height=50, style={'width': '50px'}),
    StreamlitFlowNode('14', (100, 250), {'content': 'Node 1-4'}, 'input', source_position='right', draggable=False,
                      width=100, height=50),

    StreamlitFlowNode(id='20', pos=(290, 90), data={'content': "Node 2-0"},  node_type='output', draggable=False,
                      width=120, height=220),
    StreamlitFlowNode(id='21', pos=(300, 100), data={'content': "Node 2-1"},  node_type='output', target_position='left', draggable=False,
                      width=100, height=25),
    StreamlitFlowNode('22', (300, 150), {'content': 'Node 2-2'}, 'input', 'left', draggable=False,
                      width=100, height=25),
    StreamlitFlowNode('23', (300, 200), {'content': 'Node 2-3'}, 'output', target_position='left', draggable=False,
                      width=100, height=25, style = {'padding-top' : 0}),
    StreamlitFlowNode('24', (300, 250), {'content': '<p style="margin: 0; padding: 0; font-weight: 400;">Node 2-4</p>'}, 'output', target_position='left', draggable=False,
                      width=100, height=25, style={ "padding": 0 }),
]
```

All the best...
