### ISSUE TITLE
Hide React flow water mark

### ISSUE THREAD

**Issue by shuZro** [dkapur17/streamlit-flow#7]
Is there a way to hide the react flow water mark?

**Comment by dkapur17** [comment]
While it is supported in reactflow, the option has not been implemented in this library yet. Will add this to the next release.

**Comment by shuZro** [comment]
Do you have plans for editable text on the nodes? And also getting the state of the flow chart on change to python?

**Comment by dkapur17** [comment]
It's a little hard to accommodate various types of nodes into the library since ReactFlow expects you to write JSX for any custom node you want to make, but there is no easy way to bring this paradigm into python. Regardless, as of now there is no plan to give nodes the ability to contain arbitrary components, which includes editable text boxes.

As for the roadmap - there isn't one yet 😬, at least nothing concrete. It's more of whatever comes up as feature requests or some new features that I feel might be useful to add.

**Comment by dkapur17** [comment]
Added support for this in `v1.2.8`. Use the `hide_watermark` property on `streamlit_flow` to show or hide it as needed.
